-- ==============================================================================
-- THREATLEN AI - SUPABASE CLOUD DATABASE SCHEMA & INITIALIZATION
-- Run this script in the Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)
-- ==============================================================================

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    role TEXT NOT NULL DEFAULT 'Security Analyst',
    status TEXT DEFAULT 'Active',
    last_login TEXT,
    avatar TEXT,
    created_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- 2. Create Threats Table
CREATE TABLE IF NOT EXISTS public.threats (
    id TEXT PRIMARY KEY,
    source_ip TEXT NOT NULL,
    dest_ip TEXT NOT NULL,
    port INTEGER NOT NULL,
    protocol TEXT NOT NULL,
    requests INTEGER NOT NULL,
    failed_logins INTEGER NOT NULL,
    anomaly_score NUMERIC(5,2) NOT NULL,
    threat_type TEXT NOT NULL,
    risk TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    accounts_targeted INTEGER DEFAULT 1,
    country TEXT DEFAULT 'EXTERNAL',
    target_service TEXT DEFAULT 'Unknown'
);

-- 3. Create Incidents Table
CREATE TABLE IF NOT EXISTS public.incidents (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    severity TEXT NOT NULL,
    status TEXT DEFAULT 'Open',
    assigned_to TEXT DEFAULT 'AI Auto-Task',
    events_count INTEGER DEFAULT 1,
    source_ip TEXT DEFAULT 'Unknown',
    summary TEXT,
    created_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- 4. Create Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    details TEXT,
    user_id TEXT DEFAULT 'SYSTEM',
    timestamp TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- 5. Create Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Enables open read/write access for the API key / frontend service
-- ==============================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.threats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Users policies
DROP POLICY IF EXISTS "Allow public access to users" ON public.users;
CREATE POLICY "Allow public access to users" ON public.users FOR ALL USING (true) WITH CHECK (true);

-- Threats policies
DROP POLICY IF EXISTS "Allow public access to threats" ON public.threats;
CREATE POLICY "Allow public access to threats" ON public.threats FOR ALL USING (true) WITH CHECK (true);

-- Incidents policies
DROP POLICY IF EXISTS "Allow public access to incidents" ON public.incidents;
CREATE POLICY "Allow public access to incidents" ON public.incidents FOR ALL USING (true) WITH CHECK (true);

-- Audit logs policies
DROP POLICY IF EXISTS "Allow public access to audit_logs" ON public.audit_logs;
CREATE POLICY "Allow public access to audit_logs" ON public.audit_logs FOR ALL USING (true) WITH CHECK (true);

-- Settings policies
DROP POLICY IF EXISTS "Allow public access to settings" ON public.settings;
CREATE POLICY "Allow public access to settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- INITIAL TELEMETRY SEED DATA (Only inserted if tables are empty)
-- ==============================================================================

-- Baseline Users
INSERT INTO public.users (id, name, email, password_hash, role, status, last_login, avatar, created_at)
VALUES 
    ('USR-01', 'Dr. Elena Vance', 'analyst@ibm.security', 'pbkdf2:sha256:sample', 'Lead SOC Analyst', 'Active', '2026-09-22 15:10', 'EV', '2026-09-20 10:00:00'),
    ('USR-02', 'Marcus Holloway', 'marcus.h@ibm.security', 'pbkdf2:sha256:sample', 'Security Analyst', 'Active', '2026-09-22 14:45', 'MH', '2026-09-20 10:00:00'),
    ('USR-03', 'Sarah Connor', 's.connor@ibm.security', 'pbkdf2:sha256:sample', 'Incident Responder', 'Active', '2026-09-22 13:20', 'SC', '2026-09-20 10:00:00'),
    ('USR-04', 'Devon Miles', 'devon.m@ibm.security', 'pbkdf2:sha256:sample', 'Viewer', 'Inactive', '2026-09-18 11:00', 'DM', '2026-09-20 10:00:00')
ON CONFLICT (id) DO NOTHING;

-- Baseline Threats
INSERT INTO public.threats (id, source_ip, dest_ip, port, protocol, requests, failed_logins, anomaly_score, threat_type, risk, timestamp, status, accounts_targeted, country, target_service)
VALUES 
    ('THR-9021', '192.168.1.50', '10.0.4.12', 22, 'SSH', 500, 147, 0.94, 'Brute Force', 'Critical', '2026-09-20 17:14:02', 'Active', 18, 'US-EAST', 'OpenSSH 8.9'),
    ('THR-9022', '10.0.12.88', '10.0.2.1', 443, 'HTTPS', 14200, 2, 0.88, 'DoS-like Pattern', 'Critical', '2026-09-20 17:12:45', 'Investigating', 1, 'INTERNAL', 'Nginx Gateway'),
    ('THR-9023', '172.16.42.11', '10.0.10.15', 3389, 'RDP', 840, 89, 0.81, 'Abnormal Login', 'High', '2026-09-20 17:08:19', 'Active', 4, 'EU-WEST', 'WinRDP'),
    ('THR-9024', '192.168.1.105', '10.0.1.0/24', 80, 'TCP', 3400, 0, 0.76, 'Port Scanning', 'High', '2026-09-20 16:55:00', 'Mitigated', 0, 'ASIA-PAC', 'Subnet Sweep'),
    ('THR-9025', '45.142.120.9', '10.0.4.50', 8080, 'HTTP', 120, 12, 0.65, 'Suspicious IP Behaviour', 'Medium', '2026-09-20 16:42:11', 'Investigating', 2, 'RU-NET', 'Apache Tomcat'),
    ('THR-9026', '10.0.5.112', '10.0.4.12', 443, 'HTTPS', 45, 1, 0.22, 'Normal Baseline', 'Low', '2026-09-20 16:30:00', 'Closed', 1, 'INTERNAL', 'Internal Portal'),
    ('THR-9027', '198.51.100.42', '10.0.2.80', 21, 'FTP', 620, 41, 0.79, 'Brute Force', 'High', '2026-09-20 16:15:33', 'Active', 6, 'SA-EAST', 'vsftpd')
ON CONFLICT (id) DO NOTHING;

-- Baseline Incidents
INSERT INTO public.incidents (id, title, severity, status, assigned_to, events_count, source_ip, summary, created_at)
VALUES 
    ('INC-2026-00421', 'Possible Brute Force Attack on Internal SSH Cluster', 'Critical', 'Open', 'Dr. Elena Vance', 147, '192.168.1.50', 'High volume of failed authentication requests targeted against root and admin accounts within 120 seconds.', '2026-09-20 17:14:02'),
    ('INC-2026-00420', 'Internal Subnet Port Sweep Activity Detected', 'High', 'In Progress', 'Marcus Holloway', 3400, '192.168.1.105', 'Sequential TCP SYN requests sent across 254 endpoints on management subnet.', '2026-09-20 16:55:00'),
    ('INC-2026-00419', 'Volumetric Traffic Anomaly on Public API Gateway', 'Critical', 'Investigating', 'Sarah Connor', 14200, '10.0.12.88', 'Requests/sec exceeded baseline by 840%. Potential HTTP Flood or misconfigured daemon.', '2026-09-20 17:12:45')
ON CONFLICT (id) DO NOTHING;

-- Baseline Audit Log
INSERT INTO public.audit_logs (action, details, user_id, timestamp)
VALUES ('SYSTEM_BOOT', 'ThreatLen AI Cloud Telemetry connected to Supabase PostgreSQL.', 'SYSTEM', to_char(now(), 'YYYY-MM-DD HH24:MI:SS'));

-- Baseline Default Settings
INSERT INTO public.settings (key, value, updated_at)
VALUES 
    ('detection_preset', 'balanced', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('contamination_rate', '0.05', to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('auto_quarantine', 'true', to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
ON CONFLICT (key) DO NOTHING;
